---
title: "Proteome analysis SMEG"
author: "Marie Locard-Paulet"
date: '`r date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
require(ggplot2)
require(corrplot)
require(gplots)
require(knitr)
```

Input: "RAW/Quantified proteins 290917.txt"
I have replaced the "#", "'" and tab in the excel file (Proline export) before saving in tab-delimited format.

```{r}
input <- read.table("RAW/Quantified proteins 290917.txt", header = T, sep = "\t")
mapping <- read.table("RAW/Quantified proteins 290917_Mapping.txt", header = T, sep = "\t")
mapping$Label <- paste0(mapping$cellular.compartment, "-", mapping$biological.replicate, "-", mapping$technical.replicate)
```

```{r}
mat <- input[,c(2,which(grepl("abundance", names(input))))]
mat <- mat[,which(!grepl("raw_", names(mat)))]
na <- mat[,1]
mat <- as.matrix(mat[,2:ncol(mat)])
row.names(mat) <- na
image(log(mat))
```

Pairwise plots:
```{r, eval = F}
pairs(log(mat[,1:16]), pch = ".", main = "plasma membrane")
pairs(log(mat[,17:32]), pch = ".", main = "secretome")
pairs(log(mat[,33:48]), pch = ".", main = "mycomembrane")
pairs(log(mat[,49:64]), pch = ".", main = "cytoplasm")
```

```{r}
M <- cor(log(mat[complete.cases(mat),]))
corrplot(M, method="color")
par(mar = c(8,2,4,1))
boxplot(log(mat), las = 2, cex = 0.5, main = "log-transformed abundance across runs")

heatmap.2(log(mat[complete.cases(mat),]))

pca <- prcomp(log(mat[complete.cases(mat),]), center = F, scale = F)

tab <- summary(pca)
kable(tab$importance[,1:3])


gtab <- pca$rotation
gtab <- as.data.frame(gtab)
gtab$Condition <- mapping$cellular.compartment[match(sub("abundance_Laura.", "", colnames(mat)), mapping$Sample.name)]
gtab$Replicate <- mapping$biological.replicate[match(sub("abundance_Laura.", "", colnames(mat)), mapping$Sample.name)]
gtab$Replicate <- as.character(gtab$Replicate)

ggplot(gtab, aes(x = PC1, y = PC2, col = Condition, label = Replicate, shape = Replicate)) + theme_bw() + geom_point()


```