---
title: "Proteomic analysis SMEG"
author: "Marie Locard-Paulet"
date: '`r date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r, message=F}
require(ggplot2)
require(corrplot)
require(gplots)
require(knitr)
require(reshape2)
require(VIM) # visualisation missing data
require(multcompView) # extract_p()
require(ggrepel)
```

```{r}
# Create colour function for the heatmap:
colvec <- c("darkgreen", "yellow", "red")
pal <- colorRampPalette(colvec)

mlpplot90 <- function(plot) {
        print(plot + theme_minimal() + scale_fill_brewer(palette = "Set1") + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 8)))
}
```

```{r, echo=T}
load("Data/Data01.Rdata")
```

# ANOVA

I create a matrix with the "present/absent" information:

```{r}
matpa <- export[,substr(names(export), 1, 2)=="In"]
```

I remove from the matrix the rows with only missing values:
  
```{r}
matpa <- matpa[sapply(1:nrow(mat), function(x) {length(mat[x,][is.na(mat[x,])])})<ncol(mat),]
mat <- mat[sapply(1:nrow(mat), function(x) {length(mat[x,][is.na(mat[x,])])})<ncol(mat),]
colnames(mat) <- sub("_woMissingVal", "", colnames(mat))
```

For each protein in the table, I perform an anova:
```{r, eval = F}
matmean <- matrix(ncol = 4, nrow = nrow(mat))
colnames(matmean) <- sort(unique(substr(colnames(mat), 1, 2)))
rownames(matmean) <- rownames(mat)

vecpval <- vector(length = nrow(mat))

matpTukey <- matrix(ncol = 6, nrow = nrow(mat))
colnames(matpTukey) <- sort(c("CP-CF", "CW-CF", "MP-CF", "CW-CP", "MP-CP", "MP-CW"))
rownames(matpTukey) <- rownames(mat)
matDiff <- matrix(ncol = 6, nrow = nrow(mat))
colnames(matDiff) <- sort(c("CP-CF", "CW-CF", "MP-CF", "CW-CP", "MP-CP", "MP-CW"))
rownames(matDiff) <- rownames(mat)

for (i in 1:nrow(mat)) {
  prot <- rownames(mat)[i]
  mattemp <- melt(mat[i,])
  mattemp$condition <- substr(rownames(mattemp), 1, 2)
  a <- aov(value~condition, data = mattemp)
  a1 <- anova(a)
  pval <- a1$`Pr(>F)`[1]
  m <- model.tables(a, "means")$tables$condition # mean per condition
  m <- m[order(names(m))]
  Tuk <- TukeyHSD(a)
  pTuk <- extract_p(Tuk)$condition
  pTuk <- pTuk[order(names(pTuk))]
  Diff <- Tuk$condition[,1]
  Diff <- Diff[order(names(Diff))]
  matmean[i,] <- m
  vecpval[i] <- pval
  if (sum(names(Diff)==names(pTuk) & names(pTuk)==colnames(matDiff))==6) {
    matDiff[i,] <- Diff
    matpTukey[i,] <- pTuk
  } else {
    print("error")
  }
}
# Remove the Diff et pTuk values when the protein is not detected in all the biological replicates in both compartments compared:
correspondance <- data.frame("column" = 1:ncol(matDiff), "Comp1" = c(1, 2, 2, 3, 3, 3), "Comp2" = c(4,4,1,4,1,2))
for (i in 1:ncol(matDiff)) {
  matDiff[matpa[,correspondance[i,2]]==0 & matpa[,correspondance[i,3]]==0,i] <- NA 
  matpTukey[matpa[,correspondance[i,2]]==0 & matpa[,correspondance[i,3]]==0,i] <- NA
}

save(list = c("matmean", "matDiff", "matpTukey", "vecpval"), file = "Data/Data02.Rdata")
```

```{r}
load(file = "Data/Data02.Rdata")
```

Volcano plot per comparison:

We map the proteins of interest (in colour).

```{r}
# Table of proteins of interest:
tabprotLaura <- read.table("RAW/ProteinOfInterest_20171013.txt", sep = "\t", header = T)
```

```{r}
# Change names of columns of matpa:
colnames(matpa) <- c("CP", "CW", "MP", "CF")
```

```{r}
for (i in 1:ncol(matDiff)) {
  gtab <- data.frame("Diff"=matDiff[,i], "pTukey"=matpTukey[,i])
  vectemp <- strsplit(colnames(matDiff)[i], "-")[[1]]
  gtab$Detection <- ifelse((matpa[,colnames(matpa)==vectemp[1]]==0 | matpa[,colnames(matpa)==vectemp[2]]==0), "Absent in one condition", "Present")
  gtab$Gene <- tabprotLaura$GeneNameLaura[match(rownames(gtab), tabprotLaura$accession)]
  gtab$col <- ifelse(!is.na(gtab$Gene), "Regulated", "Not regulated")
  vec <- tabprotLaura$Comments[match(gtab$Gene, tabprotLaura$GeneNameLaura)]
  gtab$col[vec=="FasII"] <-  "FasII"
  
  gtab <- gtab[order(gtab$col),]
  ti <- colnames(matDiff)[i]
  #g <- ggplot(gtab, aes(x = Diff, y = -log10(pTukey), col = col, label = Gene)) + geom_point(alpha = 0.6) + ggtitle(ti) + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + theme_bw() + scale_color_manual(values = c("red", "grey80", "dodgerblue4")) + geom_text_repel()
  g <- ggplot(subset(gtab, gtab$Detection=="Present"), aes(x = Diff, y = -log10(pTukey), col = col, label = Gene)) + geom_point(data = subset(gtab, gtab$Detection=="Absent in one condition"), aes(x = Diff, y = -log10(pTukey)), col = "mediumaquamarine", alpha = 0.6)  + geom_point(alpha = 0.6) + ggtitle(ti) + geom_vline(xintercept = 0) + geom_hline(yintercept = 0) + theme_bw() + scale_color_manual(values = c("red", "grey80", "dodgerblue4")) + geom_text_repel()
  print(g)
}
```

Save export table in the output:

```{r}
colnames(matDiff) <- paste0(colnames(matDiff), "_Diff")
colnames(matpTukey) <- paste0(colnames(matpTukey), "_pTukey")
colnames(matmean) <- paste0(colnames(matmean), "_Mean")

mattot <- cbind(matmean, matDiff, "pvalAnova" = vecpval, matpTukey)
mattot <- cbind(mattot, "accession"=rownames(mattot))
export <- merge(export, mattot, by = "accession", all = T)

write.table(export, row.names = F, "Output/ExportedTableAfterStat.txt", sep = "\t")
save(list = c("export", "mapping", "mattot"), file = "Data/Data03.Rdata")
```

# Heatmap of proteins of interest

```{r}
hm <- export[export$accession %in% tabprotLaura$accession,grepl("_MeanTech", names(export))]
hm$accession <- export$accession[export$accession %in% tabprotLaura$accession]
hm$gene <- tabprotLaura$GeneNameLaura[match(hm$accession, tabprotLaura$accession)]
hm$FasII <- tabprotLaura$Comments[match(hm$accession, tabprotLaura$accession)]

hm2 <- as.matrix(hm[,1:16])
rownames(hm2) <- hm$accession
hm2[is.na(hm2)] <- 0
colnames(hm2) <- sub("_MeanTech", "", colnames(hm2))

fasII <- ifelse(hm$FasII=="FasII", 2, 1)
heatmap.2(scale(hm2, center = F, scale = F), ColSideColors = matcol[match(substr(colnames(mat), 1, 2), matcol[,2]),1], col = pal(300), trace = "none", mar = c(4,13), breaks = c(0, seq(from = 10, to = 35, length.out = 300)), colRow = fasII)
```

*******************************************************************************
```{r}
sessionInfo()
```
